Repository ajou-capstone/campus-market-android, pull requests merged in 2024-11, with the labels that each got.

#19 [CM-8.3] 검색 결과 UI & 로직 제작
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/feature/TradeApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/category/CategoryListRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/trade/SearchTradeListRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/trade/MockTradeRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/trade/RealTradeRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/feature/category/CategoryList.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/feature/TradeRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/feature/trade/GetCategoryListUseCase.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/MainDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/TradeViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/TradeSearchConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/TradeSearchDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/TradeSearchScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/result/TradeSearchResultArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/result/TradeSearchResultConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/result/TradeSearchResultData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/result/TradeSearchResultDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/result/TradeSearchResultScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/result/TradeSearchResultViewModel.kt
Labels: state: in review, priority: medium, develop: feature

#21 Version 0.2.0
  gradle/libs.versions.toml
Labels: state: in review, priority: low

#23 [CM-8.3] 검색 결과 UI & 로직 제작
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/feature/TradeApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/trade/CategoryListRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/trade/MockTradeRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/trade/RealTradeRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/feature/trade/CategoryList.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/feature/TradeRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/feature/trade/GetCategoryListUseCase.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/TradeScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/TradeScreenArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/TradeViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/TradeSearchData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/TradeSearchDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/TradeSearchScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/result/TradeSearchResultConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/result/TradeSearchResultData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/result/TradeSearchResultDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/result/TradeSearchResultScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/result/TradeSearchResultViewModel.kt
Labels: priority: medium, develop: refactoring, develop: bug fix

#25 [CM-40.1] ScheduleTable 제작
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/feature/schedule/Schedule.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/common/table/ScheduleTable.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/common/table/ScheduleTableData.kt
Labels: state: in review, priority: high, develop: feature

#24 [CM-37.1] 개인 시간표 확인 UI & 로직
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/feature/ScheduleApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/schedule/EditScheduleReq.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/schedule/GetScheduleRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/schedule/MockScheduleRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/schedule/RealScheduleRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/feature/ScheduleRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/feature/schedule/EditScheduleUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/feature/schedule/GetScheduleUseCase.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/HomeScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/HomeType.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/ScheduleArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/ScheduleConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/ScheduleData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/ScheduleViewModel.kt
  presentation/src/main/res/drawable/ic_calendar.xml
Labels: state: in review, priority: high, develop: feature

#26 [CM-38.2] 개인 시간표 수정 UI & 로직 제작
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/feature/ChatApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/chat/GetRecentMessageIdListRes.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/common/base/BaseViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/ScheduleArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/ScheduleViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/edit/ScheduleEditArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/edit/ScheduleEditData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/edit/ScheduleEditScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/edit/ScheduleEditViewModel.kt
Labels: state: in review, priority: medium, priority: high

#22 [CM-44.1] 상품 등록 UI & 로직 제작
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/feature/TradeApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/nonfeature/FileApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/trade/PostTradeReq.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/trade/PostTradeRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/file/GetPreSignedUrlListRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/trade/MockTradeRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/trade/RealTradeRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/file/MockFileRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/nonfeature/file/PreSignedUrl.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/feature/TradeRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/feature/trade/PostNewTradeUseCase.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/MainDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/chatroom/chat/ChatViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/TradeScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/post/TradePostArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/post/TradePostConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/post/TradePostData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/post/TradePostDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/post/TradePostScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/post/TradePostViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/profile/RegisterProfileViewModel.kt
Labels: state: in progress, priority: medium, develop: feature

#28 [CM-39.1] 다른 사용자의 시간표를 확인하는 UI & 로직 제작
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/local/database/message/MessageEntity.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/feature/ChatApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/chat/MessageReq.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/chat/MessageRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/chat/MockChatRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/chat/RealChatRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/feature/chat/Message.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/MainDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/HomeArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/HomeScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/HomeViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/chatroom/ChatRoomScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/chatroom/chat/ChatArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/chatroom/chat/ChatScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/chatroom/chat/ChatViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/compare/ScheduleCompareArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/compare/ScheduleCompareConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/compare/ScheduleCompareData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/compare/ScheduleCompareDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/compare/ScheduleCompareScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/compare/ScheduleCompareViewModel.kt
Labels: state: in review, priority: medium, develop: feature

#32 QA Bug Fix
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/local/database/message/MessageDao.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/feature/ChatApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/feature/TradeApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/chat/GetMessageListByIdRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/chat/GetRoomRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/chat/MessageReq.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/chat/MessageRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/trade/DeletedLikedItemRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/trade/PostTradeRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/trade/SearchTradeListRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/chat/RealChatRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/trade/MockTradeRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/feature/trade/SummarizedTrade.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/HomeViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/chatroom/ChatRoomViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/chatroom/chat/ChatViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/ScheduleViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/common/table/ScheduleTable.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/edit/ScheduleEditScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/schedule/edit/ScheduleEditViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/TradeScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/info/TradeInfoArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/info/TradeInfoScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/post/TradePostArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/post/TradePostScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/post/TradePostViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/search/result/TradeSearchResultScreen.kt
Labels: state: in review, priority: high, develop: bug fix

#34 [CM-20.2] 채팅 웹소켓 로직 FIX
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/chatroom/ChatRoomViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/chatroom/chat/ChatViewModel.kt
Labels: state: in review, priority: high, develop: bug fix

#46 [CM-29.1] 최근 작성 게시글 보는 UI & 로직
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/mypage/RecentTradeRes.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/MainDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/MyPageScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/recent_trade/MyRecentTradeArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/recent_trade/MyRecentTradeConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/recent_trade/MyRecentTradeData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/recent_trade/MyRecentTradeDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/recent_trade/MyRecentTradeScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/recent_trade/MyRecentTradeViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/userprofile/UserProfileScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/userprofile/UserProfileViewModel.kt
Labels: state: in review, priority: high, develop: feature

#49 [CM-41.1] 문의 사항을 입력받는 화면 구성 - in Progress
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/feature/MyPageApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/mypage/InquiryCategoryListRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/mypage/InquiryContentsReq.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/mypage/InquiryInfoRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/feature/mypage/UserInquiryRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/mypage/RealMyPageRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/mypage/paging/InquiryPagingSource.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/feature/mypage/InquiryCategoryList.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/feature/mypage/InquiryInfo.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/feature/mypage/UserInquiry.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/feature/MyPageRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/feature/myprofile/GetInquiryCategoryListUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/feature/myprofile/GetInquiryInfoUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/feature/myprofile/GetInquiryListUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/feature/myprofile/PostInquiryUseCase.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/MainDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/MyPageScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/InquiryArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/InquiryConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/InquiryDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/InquiryScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/InquiryViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/info/InquiryInfoArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/info/InquiryInfoConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/info/InquiryInfoData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/info/InquiryInfoDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/info/InquiryInfoScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/info/InquiryInfoViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/post/InquiryPostArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/post/InquiryPostConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/post/InquiryPostData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/post/InquiryPostDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/post/InquiryPostScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/post/InquiryPostViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/view/InquiryViewArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/view/InquiryViewConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/view/InquiryViewData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/view/InquiryViewDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/view/InquiryViewScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/mypage/inquiry/view/InquiryViewViewModel.kt
Labels: state: in progress, priority: medium, develop: feature
