Repository ajou-capstone/campus-market-android, pull requests merged in 2024-10, with the labels that each got.

#2 [CM-1.3] Firebase 구글 로그인 로직 제작
  .github/workflows/android-cd.yml
  .github/workflows/android-ci.yml
  app/proguard-rules.pro
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/login/LoginArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/login/LoginScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/login/LoginViewModel.kt
Labels: state: in review, priority: medium, develop: feature

#3 [CM-15.2] 알림 FCM 설정
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/kr/linkerbell/campusmarket/android/CampusMarketFcmService.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/tracking/MockTrackingRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/tracking/RealTrackingRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/nonfeature/TrackingRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/user/GetFcmTokenUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/user/SetFcmTokenUseCase.kt
  gradle/libs.versions.toml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/common/util/NotificationUtil.kt
  presentation/src/main/res/values/channels.xml
Labels: state: in review, priority: medium, develop: feature

#4 [CM-1.2] 로그인 UI 및 프레젠테이션 로직 제작
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/nonfeature/AuthenticationApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/nonfeature/TokenApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/environment/BaseUrlProvider.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/authentication/GetAccessTokenRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/authentication/LoginReq.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/authentication/LoginRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/authentication/RegisterReq.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/authentication/RegisterRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/authentication/token/MockTokenRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/authentication/token/RealTokenRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/nonfeature/TokenRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/authentication/LoginUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/authentication/RegistrationUseCase.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/common/theme/Theme.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/NonLoginNavGraphNavGraph.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/login/LoginScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/login/LoginViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/onboarding/OnBoardingArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/onboarding/OnBoardingConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/onboarding/OnBoardingDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/onboarding/OnBoardingScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/onboarding/OnBoardingViewModel.kt
Labels: state: in review, priority: medium, develop: feature

#5 [CM-2.1] 약관 동의 UI & 로직 제작
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/nonfeature/TermApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/term/AgreeTermListReq.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/term/GetTermListRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/term/MockTermRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/term/RealTermRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/nonfeature/term/Term.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/nonfeature/TermRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/term/AgreeTermListUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/term/GetTermListUseCase.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/NonLoginNavGraphNavGraph.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/entry/EntryArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/entry/EntryConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/entry/EntryDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/entry/EntryScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/entry/EntryViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/login/LoginScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/RegisterConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/term/RegisterTermArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/term/RegisterTermConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/term/RegisterTermData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/term/RegisterTermDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/term/RegisterTermScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/term/RegisterTermViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/splash/SplashScreen.kt
Labels: state: in review, priority: medium, develop: feature

#6 [CM-5.1] 사용자 닉네임 및 프로필 설정 UI & 로직 제작
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/nonfeature/FileApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/nonfeature/UserApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/file/GetPreSignedUrlListRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/user/GetProfileRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/user/ProfileRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/user/SetProfileReq.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/file/MockFileRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/file/RealFileRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/tracking/RealTrackingRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/user/MockUserRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/user/RealUserRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/nonfeature/file/PreSignedUrl.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/nonfeature/user/Profile.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/nonfeature/FileRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/nonfeature/UserRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/file/GetPreSignedUrlUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/file/UploadImageUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/user/SetProfileUseCase.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/NonLoginNavGraphNavGraph.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/entry/EntryScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/entry/EntryViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/profile/RegisterProfileArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/profile/RegisterProfileConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/profile/RegisterProfileDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/profile/RegisterProfileScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/profile/RegisterProfileViewModel.kt
  presentation/src/main/res/drawable/img_user_default.xml
Labels: state: in review, priority: medium, develop: feature

#9 [CM-3.1] 학교 이메일 인증에 필요한 화면 UI & 로직 제작
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/nonfeature/AuthenticationApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/authentication/SendEmailVerifyCodeReq.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/authentication/SendEmailVerifyCodeRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/authentication/VerifyEmailVerifyCodeReq.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/authentication/MockAuthenticationRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/authentication/RealAuthenticationRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/nonfeature/AuthenticationRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/authentication/SendEmailVerifyCodeUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/authentication/VerifyEmailVerifyCodeUseCase.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/common/view/textfield/TypingTextField.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/NonLoginNavGraphNavGraph.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/entry/EntryArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/entry/EntryScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/entry/EntryViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/login/LoginArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/profile/RegisterProfileArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/term/RegisterTermArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/university/RegisterUniversityArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/university/RegisterUniversityConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/university/RegisterUniversityDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/university/RegisterUniversityScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/university/RegisterUniversityViewModel.kt
Labels: state: in review, priority: medium, develop: feature

#8 [CM-5.4] 사용자 닉네임 유효성 검증
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/profile/RegisterProfileScreen.kt
Labels: state: in review, priority: low, develop: feature

#7 [CM-5.3] 갤러리 제작
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/profile/RegisterProfileScreen.kt
Labels: state: in review, priority: medium, develop: feature

#10 [CM-4.1] 학교(캠퍼스) 선택 UI & 로직
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/api/nonfeature/UserApi.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/user/GetAvailableCampusListRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/user/GetProfileRes.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/model/nonfeature/user/SetCampusReq.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/user/MockUserRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/user/RealUserRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/nonfeature/user/Campus.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/nonfeature/UserRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/user/GetAvailableCampusListUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/user/SetCampusUseCase.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/common/gallery/GalleryItemContent.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/common/gallery/GalleryScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/NonLoginNavGraphNavGraph.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/entry/EntryScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/campus/RegisterCampusArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/campus/RegisterCampusConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/campus/RegisterCampusData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/campus/RegisterCampusDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/campus/RegisterCampusScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/campus/RegisterCampusViewModel.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/nonlogin/register/term/RegisterTermScreen.kt
Labels: state: in review, priority: medium, develop: feature

#11 Version 0.1.0
  gradle/libs.versions.toml
Labels: state: in review, priority: low

#13 [Fix] BaseUrl 변경
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/network/environment/BaseUrlProvider.kt
Labels: state: in review, priority: high, develop: bug fix

#14 Version 0.1.1
  gradle/libs.versions.toml
Labels: state: in review, priority: low

#16 [CM-8.1] 검색화면 UI & 로직 제작
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/local/database/CampusMarketDatabase.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/local/database/searchhistory/SearchHistoryDao.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/local/database/searchhistory/SearchHistoryEntity.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/remote/local/di/LocalModule.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/feature/trade/MockTradeRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/tradesearch/MockSearchHistoryRepository.kt
  data/src/main/kotlin/kr/linkerbell/campusmarket/android/data/repository/nonfeature/tradesearch/RealSearchHistoryRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/model/nonfeature/tradesearch/SearchHistory.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/repository/nonfeature/SearchHistoryRepository.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/tradesearch/DeleteAllSearchHistoryByTextUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/tradesearch/DeleteSearchHistoryByTextUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/tradesearch/GetSearchHistory.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/tradesearch/GetSearchHistoryUseCase.kt
  domain/src/main/kotlin/kr/linkerbell/campusmarket/android/domain/usecase/nonfeature/tradesearch/InsertSearchHistoryUseCase.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/MainDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/HomeScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/TradeScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/tradesearch/TradeSearchArgument.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/tradesearch/TradeSearchConstant.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/tradesearch/TradeSearchData.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/tradesearch/TradeSearchDestination.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/tradesearch/TradeSearchScreen.kt
  presentation/src/main/kotlin/kr/linkerbell/campusmarket/android/presentation/ui/main/home/trade/tradesearch/TradeSearchViewModel.kt
  presentation/src/main/res/drawable/ic_clock.xml
Labels: priority: medium, develop: feature
